// Esquema de preguntas del formulario "De la idea al emprendimiento".
// Cada pregunta: { id, tipo, texto, opciones?, max?(multi), ayuda? }
// tipo: 'single' (radio), 'multi' (checkboxes), 'escala' (1-5), 'texto' (abierta)

export const BLOQUES = [
  {
    id: "bloque1",
    titulo: "Tú y tu camino emprendedor",
    preguntas: [
      {
        id: "situacion_actual",
        tipo: "single",
        texto: "¿Cuál describe mejor tu situación actual?",
        opciones: [
          "No tengo una idea todavía, pero me interesa emprender",
          "Tengo una o varias ideas",
          "Tengo una idea que quiero desarrollar",
          "Estoy trabajando activamente en una idea",
          "Estoy probando mi solución con posibles clientes",
          "Ya tengo clientes o ventas",
          "Tengo un emprendimiento funcionando y quiero hacerlo crecer",
          "Tengo un emprendimiento estructurado y estoy buscando escalarlo",
        ],
      },
      {
        id: "motivacion",
        tipo: "multi",
        max: 3,
        texto: "¿Qué te motivó a emprender? (máximo 3)",
        opciones: [
          "Resolver un problema que conozco",
          "Generar ingresos",
          "Crear independencia económica",
          "Convertir una pasión en negocio",
          "Aprovechar una oportunidad de mercado",
          "Aplicar mis conocimientos",
          "Crear impacto social",
          "Crear impacto ambiental",
          "Crear empleo",
          "Otra",
        ],
      },
      {
        id: "tiempo_trabajando",
        tipo: "single",
        texto: "¿Hace cuánto comenzaste a trabajar en esta idea?",
        opciones: [
          "Apenas estoy comenzando",
          "Menos de 3 meses",
          "3–6 meses",
          "6–12 meses",
          "1–2 años",
          "Más de 2 años",
        ],
      },
      {
        id: "acciones_realizadas",
        tipo: "multi",
        texto: "¿Qué has hecho hasta ahora para desarrollar tu idea?",
        opciones: [
          "Investigué el problema",
          "Investigué el mercado",
          "Hablé con posibles clientes",
          "Hice encuestas",
          "Realicé entrevistas",
          "Analicé competidores",
          "Diseñé un prototipo",
          "Construí un MVP",
          "Probé mi solución",
          "Publiqué mi producto/servicio",
          "Conseguí interesados",
          "Conseguí mis primeros clientes",
          "Realicé ventas",
          "Generé ingresos",
          "Conseguí aliados",
          "Busqué financiación",
          "Formalicé el negocio",
          "Todavía no he realizado acciones concretas",
        ],
      },
    ],
  },
  {
    id: "bloque2",
    titulo: "Mi idea",
    preguntas: [
      { id: "descripcion_idea", tipo: "texto", texto: "Describe tu idea de negocio en máximo 3 frases." },
      { id: "claridad_idea", tipo: "escala", texto: "¿Qué tan clara tienes actualmente tu idea? (1 = apenas la defines, 5 = la explicas con claridad)" },
      {
        id: "que_ofreces",
        tipo: "single",
        texto: "¿Qué quieres ofrecer?",
        opciones: ["Producto físico", "Producto digital", "Servicio", "Plataforma", "Aplicación/software", "Modelo de intermediación", "Experiencia", "Otro"],
      },
      {
        id: "etapa_actual",
        tipo: "single",
        texto: "¿En qué etapa consideras que está actualmente?",
        opciones: ["Solo idea", "Idea estructurada", "Prototipo", "MVP", "Piloto", "Primeras ventas", "Ventas recurrentes", "Negocio funcionando", "Negocio en crecimiento"],
      },
    ],
  },
  {
    id: "bloque3",
    titulo: "El problema",
    preguntas: [
      { id: "problema_concreto", tipo: "texto", texto: "¿Qué problema concreto quieres solucionar?" },
      { id: "quien_experimenta", tipo: "texto", texto: "¿Quién experimenta ese problema?" },
      {
        id: "frecuencia_problema",
        tipo: "single",
        texto: "¿Qué tan frecuente es este problema?",
        opciones: ["Una vez", "Ocasionalmente", "Mensualmente", "Semanalmente", "Diariamente", "Constantemente"],
      },
      { id: "importancia_problema", tipo: "escala", texto: "¿Qué tan importante es este problema para quienes lo experimentan?" },
      { id: "consecuencia_no_solucion", tipo: "texto", texto: "¿Qué ocurre si este problema no se soluciona?" },
      { id: "causa_problema", tipo: "texto", texto: "¿Por qué crees que ocurre este problema?" },
      { id: "solucion_actual", tipo: "texto", texto: "¿Cómo solucionan actualmente las personas este problema?" },
      { id: "satisfaccion_actual", tipo: "escala", texto: "¿Qué tan satisfechas están las personas con las soluciones actuales?" },
      { id: "que_cambiarias", tipo: "texto", texto: "¿Qué cambiarías de las soluciones actuales?" },
    ],
  },
  {
    id: "bloque4",
    titulo: "Cliente",
    preguntas: [
      { id: "cliente_ideal", tipo: "texto", texto: "¿Quién es tu cliente ideal?" },
      {
        id: "conocimiento_cliente",
        tipo: "multi",
        texto: "¿Qué sabes sobre ese cliente?",
        opciones: ["Edad", "Ubicación", "Ocupación", "Nivel de ingresos", "Comportamiento", "Necesidades", "Hábitos de compra", "Problemas", "Motivaciones", "No lo conozco suficientemente"],
      },
      {
        id: "como_sabes_cliente",
        tipo: "single",
        texto: "¿Cómo sabes que ese es tu cliente?",
        opciones: ["Es una suposición", "Es mi experiencia personal", "Lo observé", "Investigué", "Hice encuestas", "Hice entrevistas", "Probé con usuarios", "Ya tengo clientes de ese perfil"],
      },
      {
        id: "personas_habladas",
        tipo: "single",
        texto: "¿Con cuántas personas que podrían ser tus clientes has hablado?",
        opciones: ["1–5", "6–10", "11–20", "21–50", "Más de 50"],
      },
      { id: "aprendizaje_conversaciones", tipo: "texto", texto: "¿Qué aprendiste de esas conversaciones?" },
    ],
  },
  {
    id: "bloque5",
    titulo: "Validación",
    preguntas: [
      {
        id: "probado_solucion",
        tipo: "single",
        texto: "¿Has probado tu solución con personas reales?",
        opciones: ["No", "Sí, informalmente", "Sí, con un prototipo", "Sí, con un MVP", "Sí, con usuarios reales", "Sí, con clientes que pagan"],
      },
      {
        id: "mayor_evidencia",
        tipo: "single",
        texto: "¿Cuál ha sido tu mayor evidencia de que la idea puede funcionar?",
        opciones: [
          "No tengo evidencia todavía",
          "Personas dijeron que les gusta",
          "Personas dijeron que la comprarían",
          "Personas dejaron sus datos",
          "Personas probaron la solución",
          "Personas solicitaron el producto",
          "Conseguí preventas",
          "Conseguí clientes",
          "Conseguí ventas",
          "Tengo clientes recurrentes",
          "Tengo ingresos crecientes",
        ],
      },
      {
        id: "pruebas_realizadas",
        tipo: "single",
        texto: "¿Cuántas pruebas reales has realizado?",
        opciones: ["Ninguna", "1–5", "6–10", "11–20", "Más de 20"],
      },
      { id: "aprendizaje_pruebas", tipo: "texto", texto: "¿Qué aprendiste de las pruebas?" },
      {
        id: "cambio_resultado_aprendizaje",
        tipo: "single",
        texto: "¿Qué cambiaste en tu idea como resultado de lo aprendido?",
        opciones: ["Nada todavía", "Cambié algunos detalles", "Cambié la propuesta de valor", "Cambié el producto", "Cambié el cliente", "Cambié el modelo de negocio", "Cambié completamente la idea"],
      },
    ],
  },
  {
    id: "bloque6",
    titulo: "Producto y propuesta de valor",
    preguntas: [
      { id: "solucion_ofrecida", tipo: "texto", texto: "¿Qué solución estás ofreciendo?" },
      { id: "beneficio_principal", tipo: "texto", texto: "¿Qué beneficio principal recibe el cliente?" },
      {
        id: "frase_valor",
        tipo: "texto",
        texto: "Completa: “Ayudo a ___ que tienen el problema de ___ mediante ___ para que puedan ___.”",
      },
      { id: "por_que_elegirte", tipo: "texto", texto: "¿Por qué alguien debería elegir tu solución en lugar de otra?" },
      { id: "claridad_propuesta_valor", tipo: "escala", texto: "¿Qué tan clara consideras tu propuesta de valor?" },
    ],
  },
  {
    id: "bloque7",
    titulo: "Competencia y mercado",
    preguntas: [
      { id: "quienes_ofrecen_parecido", tipo: "texto", texto: "¿Quiénes ofrecen actualmente algo parecido?" },
      { id: "alternativas_cliente", tipo: "texto", texto: "¿Qué otras alternativas tiene tu cliente?" },
      { id: "diferenciacion", tipo: "texto", texto: "¿Qué diferencia tu solución?" },
      {
        id: "tamano_mercado",
        tipo: "single",
        texto: "¿Qué tan grande consideras el mercado al que podrías vender?",
        opciones: ["Muy pequeño", "Pequeño", "Mediano", "Grande", "Muy grande", "No lo sé todavía"],
      },
      { id: "dificultad_copiar", tipo: "escala", texto: "¿Qué tan difícil sería para otra empresa copiar tu propuesta?" },
      {
        id: "ventaja_actual",
        tipo: "multi",
        texto: "¿Qué ventaja tienes actualmente?",
        opciones: ["Conocimiento", "Tecnología", "Marca", "Comunidad", "Acceso a clientes", "Precio", "Ubicación", "Equipo", "Experiencia", "Propiedad intelectual", "Alianzas", "Ninguna clara todavía", "Otra"],
      },
    ],
  },
  {
    id: "bloque8",
    titulo: "Modelo de negocio",
    preguntas: [
      {
        id: "como_genera_ingresos",
        tipo: "single",
        texto: "¿Cómo genera o generaría ingresos tu emprendimiento?",
        opciones: ["Venta de productos", "Venta de servicios", "Suscripción", "Comisión", "Publicidad", "Licenciamiento", "Marketplace", "Otro", "Todavía no lo sé"],
      },
      {
        id: "como_definiste_precio",
        tipo: "single",
        texto: "¿Cómo has definido tu precio?",
        opciones: ["Todavía no tengo precio", "Mirando a la competencia", "Según mis costos", "Según lo que creo que el cliente pagaría", "Lo pregunté a potenciales clientes", "Lo validé con clientes", "Tengo una estrategia de precios"],
      },
      {
        id: "conoce_costos",
        tipo: "single",
        texto: "¿Conoces cuánto te cuesta producir o entregar tu solución?",
        opciones: ["No", "Tengo una estimación", "Sí, aproximadamente", "Sí, con bastante claridad"],
      },
      { id: "claridad_modelo_negocio", tipo: "escala", texto: "¿Qué tan claro tienes cómo gana dinero tu emprendimiento?" },
    ],
  },
  {
    id: "bloque9",
    titulo: "Ventas y tracción",
    preguntas: [
      {
        id: "has_vendido",
        tipo: "single",
        texto: "¿Has vendido?",
        opciones: ["No", "Estoy preparando mi primera venta", "Estoy realizando pilotos", "Hice mi primera venta", "Tengo ventas ocasionales", "Tengo ventas frecuentes", "Tengo clientes recurrentes", "Tengo ventas crecientes"],
      },
      {
        id: "clientes_reales",
        tipo: "single",
        texto: "¿Cuántos clientes reales has tenido?",
        opciones: ["1–5", "6–10", "11–25", "26–50", "Más de 50"],
      },
      {
        id: "clientes_pagaron",
        tipo: "single",
        texto: "¿Cuántos han pagado realmente?",
        opciones: ["Ninguno", "1–5", "6–10", "11–25", "26–50", "Más de 50"],
      },
      {
        id: "ingresos_actuales",
        tipo: "single",
        texto: "¿Actualmente tienes ingresos?",
        opciones: ["No", "Sí, ocasionales", "Sí, mensuales", "Sí, crecientes", "Sí, es una fuente importante de ingresos"],
      },
      {
        id: "como_consigues_clientes",
        tipo: "multi",
        texto: "¿Cómo consigues clientes?",
        opciones: ["No tengo clientes", "Recomendaciones", "Redes sociales", "WhatsApp", "Venta directa", "Página web", "Marketplace", "Publicidad", "Eventos", "Aliados", "Otro"],
      },
      { id: "claridad_proceso_ventas", tipo: "escala", texto: "¿Qué tan claro y repetible es tu proceso de ventas?" },
    ],
  },
  {
    id: "bloque10",
    titulo: "Capacidad de ejecución",
    preguntas: [
      { id: "cap_alternativas", tipo: "escala", texto: "Cuando encuentro un problema, busco diferentes alternativas antes de rendirme." },
      { id: "cap_ajustar_evidencia", tipo: "escala", texto: "Estoy dispuesto a modificar mi idea cuando la evidencia demuestra que debo hacerlo." },
      { id: "cap_ideas_acciones", tipo: "escala", texto: "Soy capaz de convertir mis ideas en acciones concretas." },
      { id: "cap_organizacion_tiempo", tipo: "escala", texto: "Organizo mi tiempo para avanzar de manera constante en mi emprendimiento." },
      { id: "cap_hablar_clientes", tipo: "escala", texto: "Me siento cómodo hablando con clientes para conocer sus necesidades." },
      { id: "cap_vender", tipo: "escala", texto: "Me siento cómodo presentando y vendiendo mi propuesta." },
      { id: "cap_buscar_apoyo", tipo: "escala", texto: "Busco activamente personas que puedan ayudarme." },
      { id: "cap_aprender_errores", tipo: "escala", texto: "Aprendo de los errores y los utilizo para mejorar." },
      { id: "cap_trabajo_equipo", tipo: "escala", texto: "Puedo trabajar con otras personas para alcanzar objetivos." },
      { id: "cap_asumir_riesgos", tipo: "escala", texto: "Estoy dispuesto a asumir riesgos razonables para desarrollar mi emprendimiento." },
    ],
  },
  {
    id: "bloque11",
    titulo: "Ecosistema",
    preguntas: [
      {
        id: "actores_importantes",
        tipo: "multi",
        texto: "¿Qué actores son importantes para tu emprendimiento?",
        opciones: ["Clientes", "Proveedores", "Competidores", "Aliados", "Empresas", "Universidades", "Gobierno", "Inversionistas", "Mentores", "Incubadoras", "Aceleradoras", "Cámaras de comercio", "Comunidades", "Otro"],
      },
      { id: "aliados_actuales", tipo: "texto", texto: "¿Qué aliados tienes actualmente?" },
      { id: "aliados_necesitas", tipo: "texto", texto: "¿Qué aliados necesitas?" },
      { id: "proveedores_necesitas", tipo: "texto", texto: "¿Qué proveedores necesitas?" },
      { id: "instituciones_ayuda", tipo: "texto", texto: "¿Qué instituciones podrían ayudarte?" },
    ],
  },
  {
    id: "bloque12",
    titulo: "¿Qué te está frenando?",
    preguntas: [
      {
        id: "principal_reto",
        tipo: "single",
        texto: "¿Cuál es tu principal reto actualmente?",
        opciones: [
          "Empezar", "Definir la idea", "Identificar el problema", "Conocer al cliente", "Validar la idea",
          "Crear el producto", "Propuesta de valor", "Modelo de negocio", "Marketing", "Ventas", "Precio",
          "Finanzas", "Organización", "Productividad", "Equipo", "Tecnología", "Proveedores",
          "Formalización", "Financiación", "Inversión", "Escalamiento", "Otro",
        ],
      },
      {
        id: "aspectos_fortalecer",
        tipo: "multi",
        max: 3,
        texto: "¿Qué otros aspectos necesitas fortalecer? (hasta 3)",
        opciones: [
          "Idea", "Problema", "Cliente", "Validación", "Producto", "Propuesta de valor", "Modelo de negocio",
          "Marketing", "Ventas", "Finanzas", "Organización", "Equipo", "Tecnología", "Financiación", "Escalamiento",
        ],
      },
      { id: "objetivo_experto_3m", tipo: "texto", texto: "Si pudieras recibir ayuda de un experto durante los próximos 3 meses, ¿qué te gustaría conseguir?" },
    ],
  },
  {
    id: "bloque13",
    titulo: "Compromiso",
    preguntas: [
      {
        id: "horas_semanales",
        tipo: "single",
        texto: "Durante los próximos 3 meses, ¿cuánto tiempo podrías dedicar semanalmente a desarrollar tu emprendimiento?",
        opciones: ["Menos de 2 horas", "2–5 horas", "5–10 horas", "10–20 horas", "Más de 20 horas"],
      },
      { id: "nivel_compromiso", tipo: "escala", texto: "¿Qué tan comprometido estás actualmente con llevar esta idea a la realidad?" },
      { id: "resultado_90_dias", tipo: "texto", texto: "¿Qué resultado concreto te gustaría conseguir en los próximos 90 días?" },
    ],
  },
];

export const TODAS_LAS_PREGUNTAS = BLOQUES.flatMap((b) => b.preguntas);
